# CNCF settings file

# List of GitHub organizations to scan for contributions (optional).
organizations:
  - aeraki-mesh
  - antrea-io
  - argoproj
  - armadaproject
  - artifacthub
  - AthenZ
  - backstage
  - bank-vaults
  - bfenetworks
  - bpfman
  - brigadecore
  - buildpacks
  - carina-io
  - cartography-cncf
  - carvel-dev
  - cdk8s-team
  - cert-manager
  - chaos-mesh
  - chaosblade-io
  - cilium
  - cloud-custodian
  - cloudevents
  - cloudnative-pg
  - clusternet
  - clusterpedia-io
  - cncf
  - cncf-projects
  - cncf-tags
  - cni-genie
  - confidential-containers
  - connectrpc
  - container2wasm
  - containerd
  - containernetworking
  - containers
  - containerssh
  - coredns
  - cortexproject
  - cozystack
  - cri-o
  - crossplane
  - crossplane-contrib
  - cubeFS
  - dapr
  - devfile
  - devspace-sh
  - devstream-io
  - dexidp
  - distribution
  - dragonflyoss
  - drasi-project
  - easegress-io
  - emissary-ingress
  - envoyproxy
  - eraser-dev
  - etcd-io
  - external-secrets
  - FabEdge
  - falcosecurity
  - flatcar
  - fluent
  - fluid-cloudnative
  - fluxcd
  - foniod
  - getporter
  - getsops
  - goharbor
  - grpc
  - headlamp-k8s
  - helm
  - hexa-org
  - hwameistor
  - hyperlight-dev
  - in-toto
  - inclavare-containers
  - inspektor-gadget
  - interTwin-eu
  - istio
  - jaegertracing
  - k0sproject
  - k3s-io
  - k8gb-io
  - k8sgpt-ai
  - k8up-io
  - kairos-io
  - kaito-project
  - kanisterio
  - karmada-io
  - kcl-lang
  - kcp-dev
  - kedacore
  - keptn
  - keycloak
  - keylime
  - kgateway-dev
  - kitops-ml
  - kmesh-net
  - knative
  - ko-build
  - konveyor
  - koordinator-sh
  - kptdev
  - krator-rs
  - krkn-chaos
  - krustlet
  - kuadrant
  - kuasar-io
  - kube-burner
  - kube-logging
  - kube-rs
  - kube-vip
  - kubean-io
  - kubearmor
  - kubeclipper
  - kubedl-io
  - kubeedge
  - kubefleet-dev
  - kubeflow
  - kubeovn
  - kubereboot
  - kuberhealthy
  - kubernetes
  - kubernetes-client
  - kubernetes-csi
  - kubernetes-incubator
  - kubernetes-retired
  - kubernetes-sigs
  - kubescape
  - kubeslice
  - kubestellar
  - kubevela
  - kubevirt
  - kubewarden
  - kudobuilder
  - kumahq
  - KusionStack
  - kyverno
  - lima-vm
  - linkerd
  - litmuschaos
  - longhorn
  - loxilb-io
  - merbridge
  - meshery
  - metal3-io
  - metallb
  - microcks
  - nats-io
  - networkservicemesh
  - nocalhost
  - notaryproject
  - oauth2-proxy
  - opcr-io
  - open-cluster-management-io
  - open-feature
  - open-gitops
  - open-policy-agent
  - open-telemetry
  - opencost
  - opencurve
  - openebs
  - openelb
  - openfga
  - OpenFunction
  - openGemini
  - openkruise
  - OpenObservability
  - openservicemesh
  - opentofu
  - opentracing
  - openyurtio
  - operator-framework
  - oras-project
  - oscal-compass
  - ovn-kubernetes
  - parallaxsecond
  - paralus
  - perses
  - pipe-cd
  - piraeusdatastore
  - pixie-io
  - podman-desktop
  - pravega
  - project-akri
  - project-copacetic
  - Project-HAMi
  - project-stacker
  - project-zot
  - projectcapsule
  - projectcontour
  - prometheus
  - radius-project
  - ratify-project
  - rkt
  - rook
  - runatlantis
  - runmedev
  - schemahero
  - score-spec
  - sealerio
  - sermant-io
  - serverless-devs
  - serverlessworkflow
  - service-mesh-performance
  - servicemeshinterface
  - shipwright-io
  - skooner-k8s
  - SlimPlanet
  - slimtoolkit
  - spidernet-io
  - spiffe
  - spinframework
  - strimzi
  - submariner-io
  - superedge
  - sustainable-computing-io
  - telepresenceio
  - tellerops
  - thanos-io
  - theupdateframework
  - tikv
  - tinkerbell
  - tokenetes
  - tremor-rs
  - trickstercache
  - v6d-io
  - virtual-kubelet
  - vitessio
  - volcano-sh
  - vscode-kubernetes-tools
  - wasmCloud
  - WasmEdge
  - werf
  - xline-kv
  - youki-dev

# List of GitHub repositories to scan for contributions (optional).
repositories: []

# Theme settings (required).
theme:
  base_url: "https://contribcard.cncf.io"
  email_subject: "Happy #cTENcf!"
  favicon_url: "https://raw.githubusercontent.com/cncf/contribcard-sites/refs/heads/main/cncf/favicon.ico"
  logo_url: "https://raw.githubusercontent.com/cncf/contribcard-sites/refs/heads/main/cncf/logo.svg"
  og_description: "Happy #cTENcf!"
  og_image_url: "https://raw.githubusercontent.com/cncf/contribcard-sites/refs/heads/main/cncf/og_image.png"
  og_title: "CNCF ContribCard"
  social_message: "Happy #cTENcf! Check out my #FirstContribution to CNCF projects #ContribCard #CNCF10"
